### ISSUE TITLE
IoTDB-HDFS模式 频繁出错

### ISSUE THREAD

**Issue by ppyu** [apache/iotdb#1503] opened 2020-07-16 07:10 UTC
将IoTDB的存储模式改为HDFS后成功运行，我写了一个不断插入数据的脚本，在脚本运行时手动随机查询数据，频繁报500的错误。有两种提示信息。

1. IoTDB> select * from root.XXX.device1 where time=1594870403417
     Msg: 500: null
2. IoTDB> select * from root.XXX.device1 where time=1594870403417
     Msg: 500: Cannot seek after EOF
**这个时间戳是实际插入了的**

后台日志信息如下：
2020-07-16 14:52:32,783 [pool-7-IoTDB-Query-ServerServiceImpl-thread-10] ERROR org.apache.iotdb.db.query.dataset.RawQueryDataSetWithoutValueFilter$ReadTask:107 - Something gets wrong:  
java.nio.BufferUnderflowException: null
	at java.nio.Buffer.nextGetIndex(Buffer.java:506)
	at java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:364)
	at org.apache.iotdb.tsfile.file.header.ChunkHeader.deserializeFrom(ChunkHeader.java:118)
	at org.apache.iotdb.tsfile.read.TsFileSequenceReader.readChunkHeader(TsFileSequenceReader.java:659)
	at org.apache.iotdb.tsfile.read.TsFileSequenceReader.readMemChunk(TsFileSequenceReader.java:681)
	at org.apache.iotdb.db.engine.cache.ChunkCache.get(ChunkCache.java:122)
	at org.apache.iotdb.db.query.reader.chunk.DiskChunkLoader.loadChunk(DiskChunkLoader.java:46)
	at org.apache.iotdb.db.utils.FileLoaderUtils.loadPageReaderList(FileLoaderUtils.java:150)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.unpackOneChunkMetaData(SeriesReader.java:377)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.unpackAllOverlappedChunkMetadataToCachedPageReaders(SeriesReader.java:368)
	at org.apache.iotdb.db.query.reader.series.SeriesReader.hasNextPage(SeriesReader.java:317)
	at org.apache.iotdb.db.query.reader.series.SeriesRawDataBatchReader.readPageData(SeriesRawDataBatchReader.java:151)
	at org.apache.iotdb.db.query.reader.series.SeriesRawDataBatchReader.readChunkData(SeriesRawDataBatchReader.java:143)
	at org.apache.iotdb.db.query.reader.series.SeriesRawDataBatchReader.hasNextBatch(SeriesRawDataBatchReader.java:98)
	at org.apache.iotdb.db.query.dataset.RawQueryDataSetWithoutValueFilter$ReadTask.runMayThrow(RawQueryDataSetWithoutValueFilter.java:67)
	at org.apache.iotdb.db.concurrent.WrappedRunnable.run(WrappedRunnable.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**时间戳越靠前报错几率越大，也就是说新插入的时间戳出现这个错误的几率不大**

**Comment by samperson1997** [comment] 2020-07-16 07:27
感谢使用 HDFS 模块存储 TsFile 功能及详尽的反馈，我将尽快尝试复现并修复这个报错。

Hi, thanks for using the function of TSFile storage in HDFS. I really appreciate your detailed feedback and would like to try reproduce and fix this issue ASAP.

**Comment by samperson1997** [comment] 2020-07-20 01:24
@ppyu 您好，此issue已在`rel/0.10`分支修复，请拉取最新的`rel/0.10`分支并再次尝试，如果有问题请随时联系我。近期将发布0.10.1版本，发布后即可以使用正式版。

Hi, this issue is fixed in `rel/0.10` branch. Please pull the latest branch and retry. If you meet any other problems, feel free to contact me. We will soon release 0.10.1 and you could use the formal version afterwards.

**Comment by samperson1997** [comment] 2020-07-23 04:02
This PR is closed due to no more feedback for more than 3 days. If there are any more questions, you could either reopen the issue or open a new one.

**Comment by ppyu** [comment] 2020-07-23 06:36
HDFS模式下随机查询数据报错：
Msg: 500: reach the end of the data

日志信息：
2020-07-23 14:33:07,317 [pool-5-IoTDB-RPC-Client-thread-2] ERROR org.apache.iotdb.db.service.TSServiceImpl:597 - IoTDB: Internal server error:  
org.apache.iotdb.db.exception.StorageEngineException: reach the end of the data
	at org.apache.iotdb.db.query.executor.RawDataQueryExecutor.executeWithoutValueFilter(RawDataQueryExecutor.java:78)
	at org.apache.iotdb.db.query.executor.QueryRouter.rawDataQuery(QueryRouter.java:78)
	at org.apache.iotdb.db.qp.executor.PlanExecutor.processDataQuery(PlanExecutor.java:320)
	at org.apache.iotdb.db.qp.executor.PlanExecutor.processQuery(PlanExecutor.java:176)
	at org.apache.iotdb.db.service.TSServiceImpl.createQueryDataSet(TSServiceImpl.java:929)
	at org.apache.iotdb.db.service.TSServiceImpl.internalExecuteQueryStatement(TSServiceImpl.java:567)
	at org.apache.iotdb.db.service.TSServiceImpl.executeStatement(TSServiceImpl.java:469)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:1833)
	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$executeStatement.getResult(TSIService.java:1813)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by samperson1997** [comment] 2020-07-23 10:35
您好 @ppyu ，请问您是否已经更新到最新的`re/0.10`分支？另外是否已经清空原有的文件，重新开始读写数据？如果是新写的数据文件报错，请将生成的tsfile文件作为附件我来检查一下。

Hi, have you updated to the latest `rel/0.10` branch, cleaned all old files and rewrited data? Please attach your new tsfile for me to check.

**Comment by ppyu** [comment] 2020-07-23 11:06
已经更新到最新的re/0.10分支, 并且已经清空原有文件重新开始读写数据。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-iotdb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月23日(星期四) 晚上6:35
收件人:&nbsp;"apache/incubator-iotdb"<incubator-iotdb@noreply.github.com&gt;;
抄送:&nbsp;"可以扣篮但没必要"<971106266@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-iotdb] IoTDB-HDFS模式 频繁出错 (#1503)





 
您好 @ppyu ，请问您是否已经更新到最新的re/0.10分支？另外是否已经清空原有的文件，重新开始读写数据？如果是新写的数据文件报错，请将生成的tsfile文件作为附件我来检查一下。
 
Hi, have you updated to the latest rel/0.10 branch, cleaned all old files and rewrited data? Please attach your new tsfile for me to check.

**Closed** 2020-11-27 02:40 UTC
