### ISSUE TITLE
[Bug]   Failed to execute system command  java.lang.NumberFormatException: For input string: "api95_40010"

### ISSUE THREAD

**Issue by zhengshubin** [apache/iotdb#8334] opened 2022-12-05 09:26 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/iotdb/issues) and found nothing similar.

### Version

1.0.0

### Describe the bug and provide the minimal reproduce step

I restart cluster , it occur error when I restart datanode.

### What did you expect to see?

sucess start 

### What did you see instead?

 Failed to execute system command 
java.lang.NumberFormatException: For input string: "api95_40010"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at org.apache.iotdb.consensus.iot.logdispatcher.IndexController.restore(IndexController.java:135)
        at org.apache.iotdb.consensus.iot.logdispatcher.IndexController.<init>(IndexController.java:57)
        at org.apache.iotdb.consensus.iot.logdispatcher.LogDispatcher$LogDispatcherThread.<init>(LogDispatcher.java:209)
        at org.apache.iotdb.consensus.iot.logdispatcher.LogDispatcher.lambda$new$1(LogDispatcher.java:79)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.apache.iotdb.consensus.iot.logdispatcher.LogDispatcher.<init>(LogDispatcher.java:80)
        at org.apache.iotdb.consensus.iot.IoTConsensusServerImpl.<init>(IoTConsensusServerImpl.java:129)
        at org.apache.iotdb.consensus.iot.IoTConsensus.initAndRecover(IoTConsensus.java:135)
        at org.apache.iotdb.consensus.iot.IoTConsensus.start(IoTConsensus.java:109)
        at org.apache.iotdb.db.service.DataNode.active(DataNode.java:320)
        at org.apache.iotdb.db.service.DataNode.doAddNode(DataNode.java:162)
        at org.apache.iotdb.db.service.DataNodeServerCommandLine.run(DataNodeServerCommandLine.java:95)
        at org.apache.iotdb.commons.ServerCommandLine.doMain(ServerCommandLine.java:58)
        at org.apache.iotdb.db.service.DataNode.main(DataNode.java:132)
2022-12-05 17:23:17,005 [Thread-1] INFO  o.a.i.c.conf.CommonConfig:302 - System will reject write operations when shutting down. 
2022-12-05 17:23:17,011 [1-server-thread1] INFO  o.a.r.s.i.RaftServerImpl:1045 - 1@group-000200000005: takeSnapshotAsync SnapshotManagementRequest:client-05049C4E2F77->1@group-000200000005, cid=1, seq=0, RO, null, Create: 
2022-12-05 17:23:17,012 [1-server-thread1] INFO  o.a.ratis.conf.ConfUtils:46 - raft.server.snapshot.creation.gap = 1024 (default) 
2022-12-05 17:23:17,014 [pool-34-IoTDB-ratis-bg-disk-guardian-1] INFO  o.a.i.c.r.RatisConsensus:709 - Raft group group-000200000005 took snapshot successfully 
2022-12-05 17:23:17,014 [Thread-1] INFO  o.a.i.d.s.IoTDBShutdownHook:69 - IoTDB exits. Jvm memory usage: 0 GB 251 MB 873 KB 496 B 

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by OneSizeFitsQuorum** [comment] 2022-12-05 13:13
HI, this bug is caused by our internal code handling host with `-`. We will fix it in the next version. If you're deploying 1.0 for your current environment, could you remove the - from all hosts or replace it with another symbol, such as `_`?

**Comment by OneSizeFitsQuorum** [comment] 2022-12-15 03:14
Hi, this issue have been fixed in this [PR](https://github.com/apache/iotdb/pull/8468), which will be released in 1.0.1~

**Closed** 2022-12-15 03:15 UTC
